pages/account/projects/[id]/edit.tsx

This PR fixes a bug that occurred when deleting a project that is currently the first in a user's project list (as displayed in the sidebar). The previous behaviour was that the user was redirected to a page with an invalid ID (because the project has just been deleted).
Now we filter the `projectsForSidebar` to not include the deleted project and redirect to the first project of the `remainingProjects` on project deletion.

fix(DATAHUB-223): redirect to existing project after delete

---

pages/_app.tsx
src/components/SensorsList/SensorsList.test.tsx
src/components/SensorsList/SensorsListEditRow.tsx

It was possible to submit a sensor form even when the js validation was invalid. This fixes it by ignoring clicks on submit when errors are still there.

Fix(SensorsList): Don't allow submission of sensor form when errors

---

src/components/ActiveLink/index.tsx
src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
src/components/DocsSidebar/index.tsx
src/components/Header/__snapshots__/Header.stories.storyshot
src/components/HeaderMenu/__snapshots__/HeaderMenu.stories.storyshot
src/components/HeaderMenu/index.tsx
src/components/TableOfContents/__snapshots__/TableOfContents.stories.storyshot
src/components/TableOfContents/index.tsx
src/style/global.css

This PR changes the style of active links, which were previously bold and could provoke layout shifts.
New look:

fix(ActiveLink): Fix styles of active links to avoid layout shift

---

pages/_app.tsx
pages/account/profile.tsx
pages/account/projects/[id]/edit.tsx
pages/signin.tsx
pages/signup.tsx
src/common/interfaces.ts
src/components/EditProjectForm/__snapshots__/EditProjectForm.stories.storyshot
src/components/EditProjectForm/index.tsx
src/components/ProjectCreatedInfo/__snapshots__/ProjectCreatedInfo.stories.storyshot
src/components/ProjectCreatedInfo/index.tsx
src/components/TokenDisplay/TokenDisplay.stories.tsx
src/components/TokenDisplay/TokenDisplay.test.tsx
src/components/TokenDisplay/__snapshots__/TokenDisplay.stories.storyshot
src/components/TokenDisplay/index.tsx
src/components/UserProjectsNav/__snapshots__/UserProjectsNav.stories.storyshot
src/components/UserProjectsNav/index.tsx
src/components/UserProjectsWrapper/__snapshots__/UserProjectsWrapper.stories.storyshot
src/components/UserProjectsWrapper/index.tsx
src/lib/hooks/useProjectTokens/useProjectTokens.test.tsx

These changes enable the user to refresh a project token. More specifically:
- a generic `TokenDisplay` component is added
- the component is used on the `account/projects/{id}/edit` route for refreshing the token
- the component is now also used when a project is newly created
- an unrelated fix in the `UserProjectsNav` component was also made

feat: improved token creation

---

src/components/ProjectPreview/ProjectPreview.test.tsx
src/components/ProjectPreview/index.tsx
src/lib/hooks/usePublicProjects/index.ts
src/mocks/handlers.ts

This PR adds an indication of the number of sensors on each Project Card. Getting the aggregated sum of all devices via the supabase sdk without loading all the devices isn't possible. This is only doable via the Backend. Therefore, for now, the device limit has been removed from the query. In real-case scenarios, this is probably not a problem. I already created a backend ticket to create the sum aggregation on the backend side.

feat(ProjectPreview): Show the sensors amount on each ProjectPreview

---

src/lib/hooks/useProjectTokens/useProjectTokens.test.tsx

This PR fixes a curious bug that provoked a test failure 50% of the time of a useProjectTokens test. This was due to some MSW mockings that were having an influence on different tests depending on the time of execution. I added a unique project ID to each test to ensure this couldn't happen anymore.

fix(useProjectToken): Fix useProjectTokens test failing 50% of the time

---

src/components/Dropdown/__snapshots__/Dropdown.stories.storyshot
src/components/Dropdown/index.tsx
src/components/DropdownMenu/__snapshots__/DropdownMenu.stories.storyshot

This PR fixes the bug that currently when logged in, we cannot access the user nav because the classes `opacity-0` and `opacity-100` are simultaneously present and `opacity-0` takes precedence which results in the dropdown being invisible.
In this PR it is ensured that the classes cannot exist at the same time.

fix(DATAHUB-305): ensure Dropdown opacity classes don't collide

---

pages/_app.tsx
src/components/LineChart/index.tsx
src/components/SensorsList/__snapshots__/SensorsList.stories.storyshot

This PR makes sure that line chart tooltips always snap to the nearest datapoint.

fix(STADTPULS-268): Snap tooltip to nearest datapoint

---

src/components/DataTable/__snapshots__/DataTable.stories.storyshot
src/components/DataTable/index.tsx
src/components/LineChart/index.tsx

This is a small hotfix for STADTPULS-296. To make it understandable that we currently parse all dates/times as UTC, we should also make that clear in the UI. This way, you at least understand why e.g. your values from Berlin are 2hrs off at the moment.
This solution is not ideal, but currently we receive all records as UTC time anyway, no matter where the device is located.

fix(STADTPULS-296): add UTC indicator

---

src/components/SensorsList/SensorsList.test.tsx
src/lib/formValidationUtil/formValidationUtil.test.ts
src/lib/formValidationUtil/index.ts

This PR updates the `yup` schema for device IDs. We want to make sure that inputs conform to the allowed pattern in TTN. This PR does that validation and prevents the user from inputting invalid IDs (including an update hint to what went wrong).
If the TTN pattern changes or we include other integration types, we will have to update the pattern.
We cannot rely on frontend validation only and therefore we additionally need to update our DB to only accept the new schema as well. This is yet to be done.

feat(STADTPULS-307): ensure device ID conforms to TTN pattern

---

src/components/SensorsList/WithData/WithData.test.tsx
src/components/SensorsList/WithData/index.tsx

This PR fixes the sorting of dates in the `SensorsListWithData`.
---

fix(STADTPULS-311): get correct lastRecordedAt

---

src/components/Project/index.tsx

This PR sets the last 7 days in which records were recorded as the default time range as discussed with @dnsos and @edgalindo. This ensures that, as long as a sensor recorded some data, this data will be shown and an empty chart is avoided.

fix(Project): Set last 7 days of records as default time range

---

src/components/CreateProjectForm/__snapshots__/CreateProjectForm.stories.storyshot
src/components/EditProjectForm/__snapshots__/EditProjectForm.stories.storyshot
src/components/FormSelect/FormSelect.stories.tsx
src/components/FormSelect/__snapshots__/FormSelect.stories.storyshot
src/components/FormSelect/index.tsx
src/components/Project/index.tsx

This PR ensures that selects can be both either controlled or uncontrolled while always having a value. This is important in the case an HTML form element use the form data to `onSubmit`. In this case, every input within the form must have a valid value.

fix(FormSelect): Fix select's wrong value

---

renovate.json

We have configured Renovate Bot to look for a `staging` branch, which doesn't exist in this repo. I would suggest we configure it so that it uses the `main` branch for now.
---
Closes #98

ci: use main branch for Renovate PRs

---

package-lock.json
package.json
pages/_app.tsx

This last PR before my vacation (very low effort, big benefit) adds a progress bar to the top of the page when page transitions occur. This should make the process of waiting for SSR calls to be finished and the page to be transitioned more understandable and enjoyable.
Love you all ❤️ 🌴 🏖️ See you soon!

feat(Page Transitions): Add nextjs-progressbar lib for page transitions

---

pages/account/index.tsx

This PR makes it possible to redirect to the user's account after clicking the magic link in the email:
- an `/account` route was added that first renders a "loading" profile
- we can set this route as the magic link redirect URL in Supabase
- once the user is authenticated, we redirect to the user's account `/account/[username]` (possible because we can retrieve the username from the `useAuth` hook)
Before merging:

feat(STADTPULS-430): redirect to user account after signin

---

src/components/CopyTextField/CopyTextField.test.tsx
src/components/CopyTextField/index.tsx
src/components/SensorPageHeader/index.tsx

This PR makes sure that the API URL is copied with the prefixed https protocol.

refactor(SensorPageHeader): Copy URL with protocol

---

src/components/DayPickerInput/DayPickerInput.test.tsx
src/components/DayPickerInput/index.tsx

This PR fixes the fact that date input fields wouldn't let dates be entered by typing, rather only by using the UI. This is now possible.

fix(DayPickerInput): Allow date input fields to enter date manually

---

src/components/AreaPath/index.tsx
src/components/LineChart/index.tsx
src/components/LinePath/index.tsx

This PR extends the `yScale` of the `LineChart`, `LinePath`, and `AreaChart` components to allow negative values to be displayed.

fix(LineChart): Extended Y Scale to allow negative values

---

.env.example
pages/sensors/[id].tsx
src/components/DataTable/index.tsx
src/components/LinePath/index.tsx
src/lib/hooks/useSensorRecords/index.ts
src/lib/requests/getRecordsBySensorId/getRecordsBySensorId.test.ts
src/lib/requests/getRecordsBySensorId/index.ts

Before merge:
---
This PR updates the line chart so that it can display more values. We found that **about 3000 values are the maximum** for our current charting library (visx). A `canvas`-based alternative should be explored in the future to increase the number of renderable values.
If the selected timespan has more values than the defined 3000, we show an alert informing about the limitation of the line chart.
~~Note that it is still possible to select _Alle_ even for requests that exceed 3000 values. This is because we don't want to limit accessing more than 3000 values for the download button. The button should not be limited by the rendering limits of the line chart. The alert message is shown upon selecting an _Alle_ that exceeds 3000.~~
This PR also introduces a new environment …

fix(STADTPULS-438): max rows line chart

---

pages/index.tsx

This PR enables Next's [Incremental Static Regeneration (ISR)](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) for the homepage. This means:
- The homepage is generated at build-time instead of rendered by the server on every hit
- **Load times for the homepage are reduced**: In my tests the staging URL loads the DOM in 100 - 300 ms, while stadtpuls.com needs about 1 s
- The only "dynamic" elements on the homepage are regenerated every 60 s at most (see ISR docs for details). This is relevant mainly for the stats section. I simulated adding and deleting sensors and the ISR promise of regeneration works as expected.
Note that the effect of ISR [is not visible in development](https://nextjs.org/docs/basic-features/data-fetching#runs-on-every-request-in-d …

refactor: build the homepage with ISR

---

src/components/LandingHero/__snapshots__/LandingHero.stories.storyshot
src/components/LandingHero/index.tsx

This PR fixes the stacking of the hero section. On small screens (below Tailwind's `lg`) the hero image was positioned not next to but under the intro text. However, because the image has a `z-index` of 10, the buttons of the intro text were covered by the image and therefore not clickable. This PR lifts the intro text's `z-index` to 20 on small screens.

fix: make hero buttons clickable on small screens

---

src/lib/requests/getPublicSensors/index.ts

This PR orders the sensors returned from `getPublicSensors` by creation date (newest sensors first). This makes the most recently added sensors show up first on `/sensors`.

feat(STADTPULS-471): order sensors by creation date (newest first)

---

pages/sensors/[id].tsx

This PR momentarily hides the unit on the line chart as we cannot reliably make sure the unit we mapped to the category is the one used by the user. So instead of showing "123 decibels", we just show "123".

refactor(STADTPULS-495): Hide unit on line chart

---

pages/sensors/[id].tsx
src/components/Alert/Alert.test.tsx
src/components/Alert/__snapshots__/Alert.stories.storyshot
src/components/Alert/index.tsx

This PR updates the informational Alert component to have a light gray background and updates the content of the alert message when the line chart is asked to display more than 3000 records.

feat(STADTPULS-501): less scary line chart alert

---

pages/sensors/[id].tsx
src/components/DeviceLineChartFilters/DeviceLineChartFilters.test.tsx
src/components/DeviceLineChartFilters/__snapshots__/DeviceLineChartFilters.stories.storyshot
src/components/DeviceLineChartFilters/index.tsx

This PR sets the default time filter of the line chart on the sensor page as "All", because we know have better labels and a better indication for too data-intensive charts.

refactor(STADTPULS-475): Make default time filter be "max"

---

.vscode/settings.json
pages/accounts/index.tsx
pages/sensors/index.tsx
pages/sitemap.xml.ts
src/components/AccountsGrid/AccountsGrid.test.tsx
src/lib/hooks/usePublicAccounts/index.ts
src/lib/requests/getPublicAccounts/getPublicAccounts.test.ts
src/lib/requests/getPublicAccounts/index.ts

This PR turned out a a bit differently than originally planned. STADTPULS-489 is outdated, instead we handle the accounts overview as discussed in the comments below.

feat(STADTPULS-488): sort and paginate accounts overview

---

README.md
src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
src/components/DocsSidebar/index.tsx
src/components/layouts/docs.tsx
src/style/global.css

This PR fixes the styles of the inline code elements in the docs.
**Before:**
**After:**

Better inline code styles in docs

---

pages/_app.tsx

This PR removes the Loading spinner from the loading bar in the top as it always overlaps with other elements and there is no easy quick way to move it somewhere else. The progress bar should be enough to indicate progress.

fix(STADTPULS-520): Remove spinner from loading bar

---

pages/accounts/index.tsx
pages/sensors/index.tsx
src/components/Header/__snapshots__/Header.stories.storyshot
src/components/Header/index.tsx
src/components/LandingHero/__snapshots__/LandingHero.stories.storyshot
src/components/LandingHero/index.tsx
src/components/SensorPageHeader/__snapshots__/SensorPageHeader.stories.storyshot
src/components/SensorPageHeader/index.tsx
src/components/UserInfoHeader/withData.tsx
src/style/global.css

This PR removes the `float: left;` from the header of all pages except the `/docs`. While this seems to solve the display issue, I can't quite say why. It seems that using `float: left;` creates some positioning glitch (only in Firefox).
Do you have any idea why this happens @vogelino? Also, do you remember what was the reason for adding that style while building the beta banner?

fix(STADTPULS-521): fix Firefox glitch of disappearing grid

---

src/components/AccountCard/AccountCard.test.tsx
src/components/AccountCard/__snapshots__/AccountCard.stories.storyshot
src/components/AccountCard/index.tsx
src/components/LandingSensorsSlider/__snapshots__/LandingSensorsSlider.stories.storyshot
src/components/SensorCard/SensorCard.test.tsx
src/components/SensorCard/__snapshots__/SensorCard.stories.storyshot
src/components/SensorCard/index.tsx
src/components/SensorsGrid/__snapshots__/SensorsGrid.stories.storyshot

This was missed in the first PR for STADTPULS-468.

chore(STADTPULS-468): truncate cards at 100 chars for description

---

src/lib/hooks/useSensorRecords/index.ts

This PR is a fix for STADTPULS-476. For now, we want to keep the records from refreshing when re-focussing, so this option is deactivated in SWR.
In order to observe the change, follow these steps:
1. Open the page of one of your sensors and scroll to the line chart
2. Add a record to the sensor. If using SQL, you can use `INSERT INTO records (recorded_at, measurements, sensor_id) VALUES (now(), '{42}', <YOUR_SENSOR_ID>);`
3. When re-focussing the sensor page tab, the line chart and the filters should _not_ be updated. This will only happen when updating the filters or refreshing the page.
---
Closes #178 that has an outdated fix.

fix(STADTPULS-476): don't revalidate records on focus

---

src/lib/requests/getPublicSensors/index.ts

postgrest seems to lookup all foreign keys. Since there is a fk user_id on the new extended view and the user_profiles
it gets confused https://postgrest.org/en/v9.0/api.html#hint-disambiguation

hotfix(postgrest query): Adds hint for postgrest

---

src/components/EditAddSensorModal/index.tsx
src/components/LandingSensorsSlider/__snapshots__/LandingSensorsSlider.stories.storyshot
src/components/LandingSensorsSlider/index.tsx
src/components/LandingStoriesIntro/__snapshots__/LandingStoriesIntro.stories.storyshot
src/components/LandingStoriesIntro/index.tsx
src/components/SensorPageHeader/index.tsx

This PR fixes the following issue:
When editing a sensor by dragging the map in the `EditAddSensorModal`, the updated coordinates were sometimes lagging behind the actual map viewport. To reproduce in production, you can try moving the map _slowly_ to position your sensor somewhere else. While doing this, it can occur that the viewport change is not updated in the fields that are submitted to the DB. This way the sensor location either remains the old one, or is pretty random on the map based on where the last viewport change was submitted to the fields.
**The fix**
`latitude` and `longitude` now have their own state and whenever one of them is (correctly) updated by `onViewportChange`, `setValue` is called to update the form fields. The value is now always correctly submitted.

fix(STADTPULS-564): geolocation in sensor modal

---

src/components/LandingSensorsSlider/__snapshots__/LandingSensorsSlider.stories.storyshot
src/components/LandingSensorsSlider/index.tsx
src/lib/hooks/useCuratedSensors/index.ts

Makes image on home-slider staging compatible, meaning the ids of the fake sensors on staging can also be hard-coded in order to make the previews work.

fix(STADTPULS-613): Make images staging-compatible

---

src/components/StadtpulsLogo/StadtpulsLogo.module.css

This PR makes the logo animate only once so it can never endlessly spin when stuck on hover on mobile devices

fix(STADTPULS-608): Make logo stop spinning at some point

---

src/components/LandingStoriesIntro/__snapshots__/LandingStoriesIntro.stories.storyshot
src/components/LandingStoriesIntro/index.tsx

Fix safari overlapping elements in story block

fix(STADTPULS-526): Fix safari ovelapping elements in story block

---

.github/workflows/warnForPRIntoMain.yml

This PR uses a GitHub action created in another repo, that makes sure that PRs that have another branch than staging as a source and main as a target cannot be merged (unless the checks are ignored). The repo is here:
https://github.com/technologiestiftung/warn-for-main-merge-action
~The action will not run on this PR, as it must first be merged into main in order to work.~

STADTPULS-643 : Create action that warns when a branch that isn't staging is Pull Requested against main

---

next.config.js
src/components/SensorsList/__snapshots__/SensorsList.stories.storyshot
src/components/SensorsMap/__snapshots__/SensorsMap.stories.storyshot

This PR adds the tiles.mapbox.com URL to the content security policy rules. This URL seems to be newly used by mapbox to host tiles and wasn't formerly allows in our content security policy. This might be a problem in the future.

fix(Next.js-config): Add mapbox tiles URL to content security policy

---

renovate.json

Using npm packages for hosting renovate config is deprecated

chore(renovate): Reconfigure config location
