- package-lock.json
- package.json
- pages/docs/about.mdx
- pages/docs/faq.mdx
- pages/docs/index.mdx
- pages/docs/manage-account.mdx
- pages/docs/new-account.mdx
- pages/docs/new-device.mdx
- pages/docs/new-project.mdx
- pages/docs/troubleshooting.mdx
- pages/docs/ttn-configuration.mdx
- pages/docs/view-device-data.mdx
- src/components/DocsBottomNavigation/DocsBottomNavigation.stories.tsx
- src/components/DocsBottomNavigation/DocsBottomNavigation.test.tsx
- src/components/DocsBottomNavigation/__snapshots__/DocsBottomNavigation.stories.storyshot
- src/components/DocsBottomNavigation/index.tsx
- src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
- src/components/DocsSidebar/index.tsx
- src/components/Header/__snapshots__/Header.stories.storyshot
- src/components/HeaderMenu/__snapshots__/HeaderMenu.stories.storyshot
- src/components/HeaderMenu/index.tsx
- src/components/LandingHero/__snapshots__/LandingHero.stories.storyshot
- src/components/LandingHero/index.tsx
- src/components/Project/Project.test.tsx
- src/components/Project/index.tsx
- src/components/TableOfContents/__snapshots__/TableOfContents.stories.storyshot
- src/components/TableOfContents/index.tsx
- src/components/layouts/__tests__/DocsLayout.test.tsx
- src/components/layouts/docs.tsx
- src/style/global.css
This PR adds content to the documentation, especially a step-by-step guide for the makers, indicating how to participate by adding projects and sensors.
> Feat/196 - Create documentation content for makers

- src/components/UserInfoEdit/UserInfoEdit.test.tsx
- src/components/UserInfoEdit/index.tsx
- src/lib/hooks/usePrevious/usePrevious.test.tsx
- src/lib/requests/isUsernameAlreadyTaken/index.ts
- src/lib/requests/isUsernameAlreadyTaken/isUsernameAlreadyTaken.test.ts
This PR adds a server-side verification to the UserInfoEdit component to ensures that the username isn't already taken.
> feat(isUsernameAlreadyTaken): Verify is the username is already taken

- next.config.js
This PR introduces a Content Security Policy to the project.
Note: This is a first attempt. Some more testing might be needed later on `main`. As we discussed earlier @vogelino
> feat(CSP): implement CSP (attempt)

- pages/_app.tsx
- src/components/DocsBottomNavigation/__snapshots__/DocsBottomNavigation.stories.storyshot
- src/components/DocsBottomNavigation/index.tsx
- src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
- src/components/DocsSidebar/index.tsx
- src/components/Footer/__snapshots__/Footer.stories.storyshot
- src/components/Footer/index.tsx
- src/components/TableOfContents/__snapshots__/TableOfContents.stories.storyshot
- src/components/TableOfContents/index.tsx
- src/components/layouts/docs.tsx
- src/style/global.css
This PR applies the new ci styles to the documentation page
> feat(DATAHUB-283): Docs with new ci styles

- pages/_app.tsx
- src/components/LineChart/__snapshots__/LineChart.stories.storyshot
- src/components/LineChart/index.tsx
- src/components/LinePath/index.tsx
- src/components/SensorsList/__snapshots__/SensorsList.stories.storyshot
This PR ensures that the line chart looks good even with one record only.
> fix(STADPULS-309): Buggy linechart when one record

- email-templates/invitation.html
- email-templates/signin.html
- email-templates/signup.html
This PR adds the Supabase email templates for signup, signin, and invitation to the repo. The files were first copy/pasted as-is, and then adjusted to fit the new visual identity.
Once this PR is approved we need to
> feat(STADTPULS-300): new visual identity in email templates

- email-templates/invitation.html
- email-templates/signin.html
- email-templates/signup.html
- pages/docs/faq.mdx
- pages/docs/index.mdx
- pages/docs/new-device.mdx
- pages/docs/new-project.mdx
- pages/docs/stadtpuls-account.mdx
- pages/docs/ttn-configuration.mdx
- src/components/LandingHowItWorks/__snapshots__/LandingHowItWorks.stories.storyshot
- src/components/LandingHowItWorks/index.tsx
- src/components/LandingStatsSection/__snapshots__/LandingStatsSection.stories.storyshot
- src/components/LandingStatsSection/index.tsx
another round of wording fixes, mostly lower case "du", "ihr", "deine" etc
We use lowercase writing for these from now on, e.g. "Teile dein Wissen"
> Wording fixes

- src/components/Alert/Alert.stories.tsx
- src/components/Alert/Alert.test.tsx
- src/components/Alert/__snapshots__/Alert.stories.storyshot
- src/components/Alert/index.tsx
This PR adds an Alert component with 4 types (info, error, warning & success) and a closable X icon button.
> feat(Alert): Add Alert component with close button

- src/components/DropdownMenu/DropdownMenu.stories.tsx
- src/components/DropdownMenu/DropdownMenu.test.tsx
- src/components/DropdownMenu/__snapshots__/DropdownMenu.stories.storyshot
- src/components/DropdownMenu/index.tsx
This PR adds the ability for DropdownMenus to include disabled items. This will be useful later when we will add the download link on the SensorPage.
> feat(DropdownMenu): Add ability to have disabled items in DropdownMenu

- pages/sensors/[id].tsx
- src/components/EditAccountModal/index.tsx
> feat(STADTPULS-416): display newest records at top of sensor's DataTable

- src/components/EditAddSensorModal/index.tsx
- src/components/SensorSymbol/SensorSymbol.stories.tsx
- src/components/SensorSymbol/SensorSymbol.test.tsx
- src/components/SensorSymbol/index.tsx
- src/components/UserInfoHeader/UserInfoWithData.test.tsx
- src/components/UserInfoHeader/withData.tsx
- src/lib/formValidationUtil/index.ts
This PR adds a random sensor id to the new sensor modal form so that users don't necessarily have to think about this when creating a new sensor.
> refactor(UserInfoWithData): Apply random symbol id to new sensor modal

- package-lock.json
- src/auth/Auth/index.tsx
This PR ensures that users are redirected after logging out.
PS: No tests were added because it happens in a tricky part and after many attempts to mock the right things I had to forfeit. I don't think it is that important for such a small change though.
> refactor(Logout): Redirect after logout

- pages/docs/terms.mdx
- src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
- src/components/DocsSidebar/index.tsx
- src/components/Footer/Footer.test.tsx
- src/components/Footer/__snapshots__/Footer.stories.storyshot
- src/components/Footer/index.tsx
++ adds a new page "Nutzungsbedingungen" to the documentation
++ adds new link to the new page in the footer
++ adds test for added footer link
Note: This is a first draft, likely to be extended later on. The position in the documentation is a suggestion, other ideas welcome.
> new terms page

- pages/_app.tsx
- src/components/BetaBanner/BetaBanner.stories.tsx
- src/components/BetaBanner/BetaBanner.test.tsx
- src/components/BetaBanner/__snapshots__/BetaBanner.stories.storyshot
- src/components/BetaBanner/index.tsx
- src/components/Header/__snapshots__/Header.stories.storyshot
- src/components/Header/index.tsx
- src/components/LandingHero/__snapshots__/LandingHero.stories.storyshot
- src/components/LandingHero/index.tsx
- src/components/LandingHeroImage/LandingHeroImage.module.css
- src/components/LandingHeroImage/__snapshots__/LandingHeroImage.stories.storyshot
- src/components/LandingHeroImage/index.tsx
- src/components/LandingProjectAbout/LandingProjectAbout.module.css
- src/components/StadtpulsLogo/StadtpulsLogo.module.css
- src/components/StadtpulsLogo/__snapshots__/StadtpulsLogo.stories.storyshot
- src/components/StadtpulsLogo/index.tsx
- src/style/global.css
This PR adds a BETA banner and symbol, which can be dismissed. A session storage cookie is then set that remembers that the user dismissed the banner for the whole session duration.
> refactor(STADTPULS-483): Add beta symbol and banner

- src/components/Footer/Footer.test.tsx
- src/components/Footer/__snapshots__/Footer.stories.storyshot
- src/components/Footer/index.tsx
++ added feedback link in footer
> footer link feedback

- pages/docs/index.mdx
++ added warning message in welcome page
> updated warning in docs

- src/components/Footer/__snapshots__/Footer.stories.storyshot
- src/components/Footer/index.tsx
- src/components/LandingLabAbout/__snapshots__/LandingLabAbout.stories.storyshot
- src/components/LandingLabAbout/index.tsx
++ adapted footer to new logo sorting
++ replaced tsb logo with citylab logo in "prototype" section
> update logos in footer an section

- src/components/DeviceLineChartFilters/__snapshots__/DeviceLineChartFilters.stories.storyshot
- src/components/DeviceLineChartFilters/index.tsx
Because we never display all records, only the maximum that is displayable.
> chore(STADTPULS-500): use more appropriate filter label

- src/components/SignInUpFormWrapper/SignInUpFormWrapper.test.tsx
- src/components/SignInUpFormWrapper/__snapshots__/SignInUpFormWrapper.stories.storyshot
- src/components/SignInUpFormWrapper/index.tsx
- src/components/SigninForm/__snapshots__/SigninForm.stories.storyshot
- src/components/SignupForm/__snapshots__/SignupForm.stories.storyshot
This PR removes the link to the signup page on the login page.
> chore(STADTPULS-485): Deactivate signup

- src/components/DocsSidebar/__snapshots__/DocsSidebar.stories.storyshot
- src/components/DocsSidebar/index.tsx
- src/components/layouts/docs.tsx
This PR reduces the overall text size of the docs on larger screens.
> fix(STADTPULS-517): Reduce humungous docs text size

- package.json
To prevent collision with local Docker/Supabase setup
> chore(STADTPULS-536): develop on port 3333

- src/components/UserInfoHeader/UserInfoWithData.test.tsx
- src/components/UserInfoHeader/withData.tsx
fixed a typo in the sensor modal
> fixed typo

- pages/docs/http-requests.mdx
> fixed *Stadtpuls*

- src/components/SignInUpFormWrapper/__snapshots__/SignInUpFormWrapper.stories.storyshot
- src/components/SignInUpFormWrapper/index.tsx
- src/components/SigninForm/__snapshots__/SigninForm.stories.storyshot
- src/components/SignupForm/__snapshots__/SignupForm.stories.storyshot
- src/components/SignupForm/index.tsx
++ adds target blank to "Nutzungsbedingungen" link in signup modal.
++ adds register link to the signup modal
> link fix for terms

- src/components/Tabs/__snapshots__/Tabs.stories.storyshot
- src/components/Tabs/index.tsx
- src/components/UserInfoHeader/__snapshots__/UserInfoHeader.stories.storyshot
- src/components/UserInfoHeader/index.tsx
- src/components/UserInfoHeader/withData.tsx
This PR improves the positioning of the tabs and the user stats on the user's account page on **very** small screens. See here for the improved tabs:
> fix(STADTPULS-609): account tabs mobile

- src/lib/hooks/useCuratedSensors/index.ts
> chore: remove unused sensor from Story slider

- src/components/Head/index.tsx
changed the description text for shared links
> updated link share description

- src/components/SignupForm/index.tsx
changes text in register modal from "Zwischen 3 und 20 Zeichen" to "Zwischen 4 und 20 Zeichen".
> Register min chars text

- pages/docs/http-requests.mdx
- pages/docs/view-device-data.mdx
- src/components/SensorsList/__snapshots__/SensorsList.stories.storyshot
fixed a typo
updated a paragraph in docs
> fix typo and rewording of a paragraph

- .all-contributorsrc
- README.md
https://github.com/technologiestiftung/stadtpuls-frontend/tree/docs/add-contributors-and-credits#contributors
> docs: Add credits and contributors to README

- src/components/layouts/docs.tsx
> chore(STADTPULS-782): Add shutdown notice to docs
